.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. satoshe_qt test_satoshe_qt
clean: FORCE
	$(MAKE) -C .. satoshe_qt_clean test_satoshe_qt_clean
check: FORCE
	$(MAKE) -C .. test_satoshe_qt_check
satoshe-qt satoshe-qt.exe: FORCE
	 $(MAKE) -C .. satoshe_qt
